<a href="https://colab.research.google.com/github/maneliaugust/Data-Analysis-Internship-NEXAFRICA_MC-Ncwaba/blob/main/Data_Analysis_Internship_Program_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd
import numpy as np

In [28]:
#step 1
superstore = pd.read_csv("Superstore.csv", encoding="latin1")
superstore.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [29]:
#step 2
superstore.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [30]:
superstore.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [31]:
superstore.shape

(9994, 21)

In [32]:
#step 3&4
superstore.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [33]:
superstore.duplicated().sum()

np.int64(0)

In [34]:
#step 5
#Convert to Datetime and extracting components
superstore['Order Date'] = pd.to_datetime(superstore['Order Date'])
superstore['Ship Date'] = pd.to_datetime(superstore['Ship Date'])

superstore['Order Day'] = superstore['Order Date'].dt.day
superstore['Order Month'] = superstore['Order Date'].dt.month
superstore['Order Year'] = superstore['Order Date'].dt.year

superstore['Ship Day'] = superstore['Ship Date'].dt.day
superstore['Ship Month'] = superstore['Ship Date'].dt.month
superstore['Ship Year'] = superstore['Ship Date'].dt.year
superstore

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Order Day,Order Month,Order Year,Ship Day,Ship Month,Ship Year
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,8,11,2016,11,11,2016
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,8,11,2016,11,11,2016
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,12,6,2016,16,6,2016
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,11,10,2015,18,10,2015
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,11,10,2015,18,10,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,25.2480,3,0.20,4.1028,21,1,2014,23,1,2014
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,91.9600,2,0.00,15.6332,26,2,2017,3,3,2017
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,258.5760,2,0.20,19.3932,26,2,2017,3,3,2017
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,29.6000,4,0.00,13.3200,26,2,2017,3,3,2017
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,243.1600,2,0.00,72.9480,4,5,2017,9,5,2017

In [52]:
#step 7
#Detecting Outliers: IQR Rule: Outliers = Q1 - 1.5IQR or Q3 + 1.5IQR

numeric_columns = superstore.select_dtypes(include='number').columns
superstore[numeric_columns].describe()

Q1 = superstore["Sales"].quantile(0.25)
Q3 = superstore["Sales"].quantile(0.75)
IQR = Q3 - Q1
print(IQR)

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

sales_outliers = superstore[
    (superstore['Sales'] < lower_bound) |
    (superstore['Sales'] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)
print("sales_outliers:", sales_outliers)

192.66
Q1: 17.28
Q3: 209.94
IQR: 192.66
Lower Bound: -271.71000000000004
Upper Bound: 498.93
sales_outliers:       Row ID        Order ID Order Date  Ship Date       Ship Mode  \
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class
7          8  CA-2014-115812 2014-06-09 2014-06-14  Standard Class
10        11  CA-2014-115812 2014-06-09 2014-06-14  Standard Class
11        12  CA-2014-115812 2014-06-09 2014-06-14  Standard Class
...      ...             ...        ...        ...             ...
9931    9932  CA-2015-104948 2015-11-13 2015-11-17  Standard Class
9942    9943  CA-2014-143371 2014-12-28 2015-01-03  Standard Class
9947    9948  CA-2017-121559 2017-06-01 2017-06-03    Second Class
9948    9949  CA-2017-121559 2017-06-01 2017-06-03    Second Class
9968    9969  CA-2017-153871 2017-12-11 2017-12-17  Standard Class

     Customer ID    Customer Name    Segment        Country             City  \
1       CG-12520      Claire Gute   Consumer  United States        Henderson
3       SO-20335   Sean O'Donnell   Consumer  United States  Fort Lauderdale
7       BH-11710  Brosina Hoffman   Consumer  United States      Los Angeles
10      BH-11710  Brosina Hoffman   Consumer  United States      Los Angeles
11      BH-11710  Brosina Hoffman   Consumer  United States      Los Angeles
...          ...              ...        ...            ...              ...
9931    KH-16510    Keith Herrera   Consumer  United States   San Bernardino
9942    MD-17350    Maribeth Dona   Consumer  United States          Anaheim
9947    HW-14935  Helen Wasserman  Corporate  United States     Indianapolis
9948    HW-14935  Helen Wasserman  Corporate  United States     Indianapolis
9968    RB-19435  Richard Bierner   Consumer  United States       Plainfield

      ...      Sales  Quantity Discount    Profit Order Day Order Month  \
1     ...   731.9400         3     0.00  219.5820         8          11
3     ...   957.5775         5     0.45 -383.0310        11          10
7     ...   907.1520         6     0.20   90.7152         9           6
10    ...  1706.1840         9     0.20   85.3092         9           6
11    ...   911.4240         4     0.20   68.3568         9           6
...   ...        ...       ...      ...       ...       ...         ...
9931  ...   683.3320         4     0.15  -40.1960        13          11
9942  ...   998.8200         9     0.00   29.9646        28          12
9947  ...  1925.8800         6     0.00  539.2464         1           6
9948  ...  2405.2000         8     0.00  793.7160         1           6
9968  ...   735.9800         2     0.00  331.1910        11          12

     Order Year  Ship Day  Ship Month  Ship Year
1          2016        11          11       2016
3          2015        18          10       2015
7          2014        14           6       2014
10         2014        14           6       2014
11         2014        14           6       2014
...         ...       ...         ...        ...
9931       2015        17          11       2015
9942       2014         3           1       2015
9947       2017         3           6       2017
9948       2017         3           6       2017
9968       2017        17          12       2017

[1167 rows x 27 columns]

In [55]:
Q1 = superstore["Quantity"].quantile(0.25)
Q3 = superstore["Quantity"].quantile(0.75)
IQR = Q3 - Q1
print(IQR)

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

quantity_outliers = superstore[
    (superstore['Quantity'] < lower_bound) |
    (superstore['Quantity'] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)
print("quantity_outliers:", quantity_outliers)

3.0
Q1: 2.0
Q3: 5.0
IQR: 3.0
Lower Bound: -2.5
Upper Bound: 9.5
quantity_outliers:       Row ID        Order ID Order Date  Ship Date       Ship Mode  \
113      114  CA-2014-115259 2014-08-25 2014-08-27    Second Class
139      140  CA-2016-145583 2016-10-13 2016-10-19  Standard Class
147      148  CA-2016-114489 2016-12-05 2016-12-09  Standard Class
251      252  CA-2016-145625 2016-09-11 2016-09-17  Standard Class
329      330  US-2016-141544 2016-08-30 2016-09-01     First Class
...      ...             ...        ...        ...             ...
9882    9883  CA-2014-153927 2014-08-12 2014-08-13     First Class
9895    9896  CA-2014-115049 2014-09-26 2014-10-01  Standard Class
9941    9942  CA-2017-164028 2017-11-24 2017-11-30  Standard Class
9979    9980  US-2016-103674 2016-12-06 2016-12-10  Standard Class
9984    9985  CA-2015-100251 2015-05-17 2015-05-23  Standard Class

     Customer ID       Customer Name      Segment        Country  \
113     RC-19960          Ryan Crowe     Consumer  United States
139     LC-16885      Lena Creighton     Consumer  United States
147     JE-16165      Justin Ellison    Corporate  United States
251     KC-16540     Kelly Collister     Consumer  United States
329     PO-18850     Patrick O'Brill     Consumer  United States
...          ...                 ...          ...            ...
9882    LL-16840  Lauren Leatherbury     Consumer  United States
9895    MM-17920       Michael Moore     Consumer  United States
9941    JL-15835            John Lee     Consumer  United States
9979    AP-10720          Anne Pryor  Home Office  United States
9984    DV-13465    Dianna Vittorini     Consumer  United States

               City  ...     Sales  Quantity Discount    Profit Order Day  \
113        Columbus  ...    40.096        14      0.2   14.5348        25
139       Roseville  ...    43.120        14      0.0   20.6976        13
147        Franklin  ...   384.450        11      0.0  103.8015         5
251       San Diego  ...  3347.370        13      0.0  636.0003        11
329    Philadelphia  ...   100.240        10      0.2   33.8310        30
...             ...  ...       ...       ...      ...       ...       ...
9882      Woodstock  ...   272.610        13      0.0   98.1396        12
9895        Chicago  ...   153.824        11      0.2   38.4560        26
9941  San Francisco  ...   223.580        14      0.0   87.1962        24
9979    Los Angeles  ...   437.472        14      0.2  153.1152         6
9984     Long Beach  ...    31.500        10      0.0   15.1200        17

     Order Month Order Year  Ship Day  Ship Month  Ship Year
113            8       2014        27           8       2014
139           10       2016        19          10       2016
147           12       2016         9          12       2016
251            9       2016        17           9       2016
329            8       2016         1           9       2016
...          ...        ...       ...         ...        ...
9882           8       2014        13           8       2014
9895           9       2014         1          10       2014
9941          11       2017        30          11       2017
9979          12       2016        10          12       2016
9984           5       2015        23           5       2015

[170 rows x 27 columns]

In [53]:
Q1 = superstore['Profit'].quantile(0.25)
Q3 = superstore['Profit'].quantile(0.75)

IQR = Q3 - Q1
print(IQR)

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

profit_outliers = superstore[
    (superstore['Profit'] < lower_bound) |
    (superstore['Profit'] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)
print("profit_outliers:", profit_outliers)

27.63525
Q1: 1.72875
Q3: 29.364
IQR: 27.63525
Lower Bound: -39.724125
Upper Bound: 70.816875
profit_outliers:       Row ID        Order ID Order Date  Ship Date       Ship Mode  \
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class
7          8  CA-2014-115812 2014-06-09 2014-06-14  Standard Class
10        11  CA-2014-115812 2014-06-09 2014-06-14  Standard Class
13        14  CA-2016-161389 2016-12-05 2016-12-10  Standard Class
...      ...             ...        ...        ...             ...
9957    9958  US-2014-143287 2014-11-11 2014-11-17  Standard Class
9962    9963  CA-2015-168088 2015-03-19 2015-03-22     First Class
9968    9969  CA-2017-153871 2017-12-11 2017-12-17  Standard Class
9979    9980  US-2016-103674 2016-12-06 2016-12-10  Standard Class
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class

     Customer ID     Customer Name      Segment        Country  \
1       CG-12520       Claire Gute     Consumer  United States
3       SO-20335    Sean O'Donnell     Consumer  United States
7       BH-11710   Brosina Hoffman     Consumer  United States
10      BH-11710   Brosina Hoffman     Consumer  United States
13      IM-15070      Irene Maddox     Consumer  United States
...          ...               ...          ...            ...
9957    KN-16705     Kristina Nunn  Home Office  United States
9962    CM-12655  Corinna Mitchell  Home Office  United States
9968    RB-19435   Richard Bierner     Consumer  United States
9979    AP-10720        Anne Pryor  Home Office  United States
9993    CC-12220      Chris Cortes     Consumer  United States

                 City  ...      Sales  Quantity Discount    Profit Order Day  \
1           Henderson  ...   731.9400         3     0.00  219.5820         8
3     Fort Lauderdale  ...   957.5775         5     0.45 -383.0310        11
7         Los Angeles  ...   907.1520         6     0.20   90.7152         9
10        Los Angeles  ...  1706.1840         9     0.20   85.3092         9
13            Seattle  ...   407.9760         3     0.20  132.5922         5
...               ...  ...        ...       ...      ...       ...       ...
9957     New Rochelle  ...   223.9200         4     0.00  109.7208        11
9962          Houston  ...   383.4656         4     0.32  -67.6704        19
9968       Plainfield  ...   735.9800         2     0.00  331.1910        11
9979      Los Angeles  ...   437.4720        14     0.20  153.1152         6
9993      Westminster  ...   243.1600         2     0.00   72.9480         4

     Order Month Order Year  Ship Day  Ship Month  Ship Year
1             11       2016        11          11       2016
3             10       2015        18          10       2015
7              6       2014        14           6       2014
10             6       2014        14           6       2014
13            12       2016        10          12       2016
...          ...        ...       ...         ...        ...
9957          11       2014        17          11       2014
9962           3       2015        22           3       2015
9968          12       2017        17          12       2017
9979          12       2016        10          12       2016
9993           5       2017         9           5       2017

[1881 rows x 27 columns]

In [54]:
sales_outliers[['Order ID', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']] \
    .sort_values(by='Sales', ascending=False) \
    .head(20)

,Order ID,Product Name,Sales,Quantity,Discount,Profit
2697,CA-2014-145317,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
6826,CA-2016-118689,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
8153,CA-2017-140151,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
2623,CA-2017-127180,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
4190,CA-2017-166709,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
9039,CA-2016-117121,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700
4098,CA-2014-116904,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755
4277,US-2016-107440,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930,7,0.0,2365.9818
8488,CA-2016-158841,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,5,0.0,2799.9840
6425,CA-2016-143714,Canon imageCLASS 2200 Advanced Copier,8399.976,4,0.4,1119.9968
2505,CA-2014-143917,High Speed Automatic Electric Letter Opener,8187.650,5,0.0,327.5060
165,CA-2014-139892,Lexmark MX611dhe Monochrome Laser Printer,8159.952,8,0.4,-1359.9920
683,US-2017-168116,Cubify CubeX 3D Printer Triple Head Print,7999.980,4,0.5,-3839.9904
6626,CA-2014-145541,HP Designjet T520 Inkjet Large Format Printer ...,6999.960,4,0.0,2239.9872
509,CA-2015-145352,Fellowes PB500 Electric Punch Plastic Comb Bin...,6354.950,5,0.0,3177.4750
6520,CA-2017-138289,GBC DocuBind P400 Electric Binding System,5443.960,4,0.0,2504.2216
7666,US-2016-140158,Hewlett Packard LaserJet 3310 Copier,5399.910,9,0.0,2591.9568
6340,CA-2017-143112,"3D Systems Cube Printer, 2nd Generation, Magenta",5199.960,4,0.0,1351.9896
8858,CA-2017-135909,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.960,5,0.2,1906.4850
5884,CA-2016-136301,High Speed Automatic Electric Letter Opener,4912.590,3,0.0,196.5036

In [56]:
#step 8
# Create a copy of the original dataset
cleaned_superstore = superstore.copy()

# Remove exact duplicate rows
cleaned_superstore = cleaned_superstore.drop_duplicates()

# Convert date columns to datetime
cleaned_superstore['Order Date'] = pd.to_datetime(
    cleaned_superstore['Order Date'], errors='coerce'
)

cleaned_superstore['Ship Date'] = pd.to_datetime(
    cleaned_superstore['Ship Date'], errors='coerce'
)

# Create date-related columns
cleaned_superstore['Order Day'] = cleaned_superstore['Order Date'].dt.day
cleaned_superstore['Order Month'] = cleaned_superstore['Order Date'].dt.month
cleaned_superstore['Order Year'] = cleaned_superstore['Order Date'].dt.year

cleaned_superstore['Ship Day'] = cleaned_superstore['Ship Date'].dt.day
cleaned_superstore['Ship Month'] = cleaned_superstore['Ship Date'].dt.month
cleaned_superstore['Ship Year'] = cleaned_superstore['Ship Date'].dt.year

# Check the cleaned dataset
print("Shape:", cleaned_superstore.shape)

print("\nMissing values:")
print(cleaned_superstore.isnull().sum())

print("\nData types:")
print(cleaned_superstore.dtypes)

Shape: (9994, 27)

Missing values:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
Order Day        0
Order Month      0
Order Year       0
Ship Day         0
Ship Month       0
Ship Year        0
dtype: int64

Data types:
Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
Order Day                 int32
Order Month               int32
Order Year                int32
Ship Day                  int32
Ship Month                int32
Ship Year                 int32
dtype: object